/**
 * @file CaseFileExport.js
 * @description Generates an official, legally-formatted PDF "Case File" for a specific report.
 * It works by rendering a hidden, strictly-styled HTML template in the DOM, temporarily injecting 
 * the detailed AI voting logs (fetched live from Supabase), and then using html2canvas/jsPDF 
 * to capture and export the document.
 */

import React, { useRef } from 'react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { supabase } from '../../supabaseClient'; 

// --- UNIVERSAL SVG ICON MAPPING ---
const SVGIcons = {
  FileText: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
};

const CaseFileExport = ({ report, userProfile, isEn }) => {
  const exportRef = useRef(null);

  if (!report) return null;

  // --- METADATA EXTRACTION ---
  // Safely extract properties whether it's a standard report or a direct assignment
  const isAssignment = report._table === 'assignments';
  const platform = report.platform || report.reports?.platform || 'Unknown';
  const category = report.category || report.reports?.category || 'Uncategorized';
  const content = isAssignment ? (report.description || report.content) : (report.content || report.reports?.content);
  const imageUrl = report.image_url || report.reports?.image_url;
  const driveLink = report.drive_link || report.reports?.drive_link;
  
  const aiReasoning = report.ai_reasoning || report.reports?.ai_reasoning;
  const aiConfidence = report.ai_confidence || report.reports?.ai_confidence || 0;
  const hasFailures = report.routing_metadata?.failures > 0;

  // Extract the top-level consensus notes generated by the System Orchestrator
  const systemNotes = aiReasoning 
    ? aiReasoning.split('\n').filter(line => line.startsWith('[SYSTEM')) 
    : [];

  /**
   * Orchestrates the PDF generation process.
   * Fetches missing data, injects it into the hidden template, captures the canvas, and downloads.
   */
  const handleExportPDF = async () => {
    const element = exportRef.current;
    if (!element) return;

    try {
      // 1. Fetch live voting logs for this report from the database
      let votingLogs = [];
      try {
        const { data, error } = await supabase
          .from('voting_logs')
          .select('*')
          .eq('report_id', report.id)
          .order('created_at', { ascending: true });
        
        if (!error && data) {
          votingLogs = data;
        }
      } catch (dbError) {
        console.warn("Failed to fetch voting logs for PDF:", dbError);
      }

      // 2. Temporarily inject the logs into the DOM *before* capturing
      // We use standard HTML string injection here because this node is normally hidden from React's typical render cycle
      const logsContainer = document.getElementById(`pdf-voting-logs-${report.id}`);
      if (logsContainer) {
        if (votingLogs.length > 0) {
          logsContainer.innerHTML = votingLogs.map(log => `
            <div style="margin-bottom: 8px;">
              <span style="color: #64748b; font-weight: bold;">[${log.engine_name}]</span>
              <span style="color: #334155;">${log.raw_vote?.reasoning || "No detailed reasoning provided."}</span>
            </div>
          `).join('');
        } else {
          logsContainer.innerHTML = `<div style="color: #94a3b8; font-style: italic;">No detailed provider logs available for this report.</div>`;
        }
      }

      // 3. Temporarily make the hidden element visible for the canvas to capture it
      element.style.display = 'block';

      // 4. Capture the HTML element as a canvas
      const canvas = await html2canvas(element, {
        scale: 2, 
        useCORS: true, // Critical for rendering Supabase images without throwing security errors
        logging: false,
      });

      // 5. Hide it again immediately so the user doesn't see the flash
      element.style.display = 'none';

      // 6. Calculate dimensions for an A4 page
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

      // 7. Add image to PDF and trigger the browser download
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      
      const fileName = `CiviWatch_CaseFile_${report.id?.substring(0,8)}_${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(fileName);

    } catch (error) {
      console.error("PDF Export Error:", error);
      alert(isEn ? "Failed to generate PDF. Check console for details." : "שגיאה ביצירת מסמך PDF.");
      element.style.display = 'none'; // Ensure it hides if the script fails midway
    }
  };

  return (
    <>
      {/* --- EXPORT ACTION BUTTON --- */}
      <button 
        onClick={handleExportPDF}
        style={{
          backgroundColor: 'transparent', color: '#38bdf8', border: '1px solid #38bdf8', padding: '4px 8px', 
          borderRadius: '4px', fontWeight: 'bold', cursor: 'pointer', display: 'flex', 
          alignItems: 'center', gap: '6px', fontSize: '0.75rem', transition: 'all 0.2s'
        }}
        onMouseOver={(e) => { e.currentTarget.style.backgroundColor = 'rgba(56, 189, 248, 0.1)' }}
        onMouseOut={(e) => { e.currentTarget.style.backgroundColor = 'transparent' }}
      >
        {SVGIcons.FileText} {isEn ? 'Export PDF' : 'ייצא ל-PDF'}
      </button>

      {/* --- HIDDEN PRINT TEMPLATE --- */}
      {/* This section is completely invisible to the user. It dictates exactly how the PDF will look. */}
      <div style={{ position: 'absolute', left: '-9999px', top: '-9999px' }}>
        <div 
          ref={exportRef} 
          style={{ 
            width: '800px', 
            padding: '40px', 
            backgroundColor: '#ffffff', 
            color: '#000000', 
            fontFamily: 'Arial, sans-serif',
            direction: isEn ? 'ltr' : 'rtl',
            display: 'none', 
            boxSizing: 'border-box'
          }}
        >
          {/* PDF HEADER */}
          <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '2px solid #0f172a', paddingBottom: '20px', marginBottom: '30px' }}>
            <div>
              <h1 style={{ margin: '0 0 5px 0', fontSize: '24px', color: '#0f172a' }}>
                CIVIWATCH GUARDIAN AI
              </h1>
              <div style={{ fontSize: '12px', color: '#475569' }}>
                OFFICIAL CASE FILE RECORD
              </div>
            </div>
            <div style={{ textAlign: isEn ? 'right' : 'left', fontSize: '12px', color: '#475569' }}>
              <div><strong>Case ID:</strong> {report.id}</div>
              <div><strong>Date Generated:</strong> {new Date().toLocaleString()}</div>
              <div><strong>Generated By:</strong> {userProfile?.display_name || userProfile?.email}</div>
            </div>
          </div>

          {/* METADATA BAR */}
          <div style={{ display: 'flex', gap: '20px', marginBottom: '30px', backgroundColor: '#f1f5f9', padding: '15px', borderRadius: '8px' }}>
            <div style={{ flex: 1 }}>
              <strong style={{ fontSize: '11px', color: '#64748b', display: 'block', textTransform: 'uppercase' }}>Platform</strong>
              <div style={{ fontSize: '16px', fontWeight: 'bold' }}>{platform}</div>
            </div>
            <div style={{ flex: 1 }}>
              <strong style={{ fontSize: '11px', color: '#64748b', display: 'block', textTransform: 'uppercase' }}>Category</strong>
              <div style={{ fontSize: '16px', fontWeight: 'bold' }}>{category}</div>
            </div>
            <div style={{ flex: 1 }}>
              <strong style={{ fontSize: '11px', color: '#64748b', display: 'block', textTransform: 'uppercase' }}>Status</strong>
              <div style={{ fontSize: '16px', fontWeight: 'bold', color: report.status === 'Verified' ? '#10b981' : '#f59e0b' }}>
                {report.status || 'Pending'}
              </div>
            </div>
          </div>

          {/* CONTENT SECTION */}
          <div style={{ marginBottom: '30px' }}>
            <h2 style={{ fontSize: '16px', color: '#0f172a', borderBottom: '1px solid #cbd5e1', paddingBottom: '8px', marginBottom: '15px' }}>
              Extracted Content / Description
            </h2>
            <div style={{ fontSize: '14px', lineHeight: '1.6', color: '#334155', backgroundColor: '#f8fafc', padding: '15px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
              {content || 'No text content provided.'}
            </div>
          </div>

          {/* EVIDENCE IMAGE (UNBLURRED FOR LEGAL PDF) */}
          {imageUrl && (
            <div style={{ marginBottom: '30px' }}>
              <h2 style={{ fontSize: '16px', color: '#0f172a', borderBottom: '1px solid #cbd5e1', paddingBottom: '8px', marginBottom: '15px' }}>
                Captured Evidence
              </h2>
              <div style={{ border: '2px solid #e2e8f0', borderRadius: '8px', padding: '10px', backgroundColor: '#fff' }}>
                 {/* RAW unblurred evidence for the legal file */}
                <img 
                  src={imageUrl} 
                  alt="Evidence Record" 
                  style={{ width: '100%', maxHeight: '400px', objectFit: 'contain' }} 
                  crossOrigin="anonymous" 
                />
              </div>
              {driveLink && (
                <div style={{ marginTop: '10px', fontSize: '12px' }}>
                  <strong>External Evidence Link:</strong> <a href={driveLink}>{driveLink}</a>
                </div>
              )}
            </div>
          )}

          {/* AI AUDIT LOG (If available) */}
          {aiReasoning && (
            <div style={{ marginBottom: '30px', pageBreakInside: 'avoid' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #cbd5e1', paddingBottom: '8px', marginBottom: '15px' }}>
                <h2 style={{ fontSize: '16px', color: '#0f172a', margin: 0 }}>
                  AI Routing & Analysis Audit
                </h2>
                <div style={{ fontSize: '14px', fontWeight: 'bold', color: '#0284c7' }}>
                  Confidence Score: {(aiConfidence * 100).toFixed(0)}%
                </div>
              </div>
              
              <div style={{ backgroundColor: '#f1f5f9', padding: '15px', borderRadius: '8px', border: '1px solid #e2e8f0', fontFamily: 'monospace', fontSize: '12px', color: '#334155' }}>
                {/* System Consensus First */}
                {systemNotes.length > 0 && (
                  <div style={{ marginBottom: '15px', paddingBottom: '15px', borderBottom: '1px dashed #cbd5e1' }}>
                    {systemNotes.map((note, index) => {
                      const isOverall = note.includes('[SYSTEM OVERALL]');
                      return (
                        <div key={index} style={{ color: isOverall ? '#0f172a' : '#059669', fontWeight: isOverall ? 'bold' : 'normal', marginBottom: '4px' }}>
                          {note}
                        </div>
                      );
                    })}
                  </div>
                )}
                
                {/* Dynamically Injected Provider Logs */}
                <div id={`pdf-voting-logs-${report.id}`}>
                   {/* Data injected here via JS just before capture */}
                </div>

                {/* Survivor Mode Alert */}
                {hasFailures && (
                  <div style={{ color: '#ef4444', fontStyle: 'italic', marginTop: '15px', borderTop: '1px dashed #cbd5e1', paddingTop: '10px' }}>
                    *(Note: {report.routing_metadata.failures} provider(s) failed. Decision based on survivors).*
                  </div>
                )}
              </div>
            </div>
          )}

          {/* CHAIN OF CUSTODY (Audit Trail) */}
          <div style={{ marginBottom: '20px', pageBreakInside: 'avoid' }}>
            <h2 style={{ fontSize: '16px', color: '#0f172a', borderBottom: '1px solid #cbd5e1', paddingBottom: '8px', marginBottom: '15px' }}>
              Operator Audit Trail
            </h2>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
              <thead>
                <tr style={{ backgroundColor: '#f1f5f9', textAlign: 'left' }}>
                  <th style={{ padding: '8px', border: '1px solid #cbd5e1' }}>Date/Time</th>
                  <th style={{ padding: '8px', border: '1px solid #cbd5e1' }}>Operator</th>
                  <th style={{ padding: '8px', border: '1px solid #cbd5e1' }}>Action</th>
                  <th style={{ padding: '8px', border: '1px solid #cbd5e1' }}>Notes</th>
                </tr>
              </thead>
              <tbody>
                {(report.additional_info || []).map((log, index) => (
                  <tr key={index}>
                    <td style={{ padding: '8px', border: '1px solid #cbd5e1' }}>{new Date(log.timestamp).toLocaleString()}</td>
                    <td style={{ padding: '8px', border: '1px solid #cbd5e1' }}>{log.actor}</td>
                    <td style={{ padding: '8px', border: '1px solid #cbd5e1' }}>{log.action}</td>
                    <td style={{ padding: '8px', border: '1px solid #cbd5e1' }}>{log.note}</td>
                  </tr>
                ))}
                {(!report.additional_info || report.additional_info.length === 0) && (
                  <tr>
                    <td colSpan="4" style={{ padding: '8px', border: '1px solid #cbd5e1', textAlign: 'center', fontStyle: 'italic' }}>
                      No manual actions recorded.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div style={{ textAlign: 'center', fontSize: '10px', color: '#94a3b8', marginTop: '40px', borderTop: '1px solid #e2e8f0', paddingTop: '15px' }}>
            CONFIDENTIAL - GENERATED BY CIVIWATCH GUARDIAN AI SYSTEM
          </div>

        </div>
      </div>
    </>
  );
};

export default CaseFileExport;